version: 1
report:
  summary: true
  output-format: json
ignore:
  # MLflow advisories - track and upgrade when compatible
  - id: 83170
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 83076
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71692
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71587
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71579
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71691
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71584
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71578
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71577
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 82294
    reason: "mlflow upgrade pending; tracked in security backlog"
  - id: 71693
    reason: "mlflow upgrade pending; tracked in security backlog"
  # ecdsa advisories - in transitive deps; evaluate replacement
  - id: 64459
    reason: "ecdsa transitive dependency; remediation under review"
  - id: 64396
    reason: "ecdsa transitive dependency; remediation under review"

